### ISSUE TITLE
assignment 1

### ISSUE THREAD

**Issue by aaronxhill** [acgaron/ML_2016#1]
I'm not sure which iteration is the definitive version. Could you move old versions to an archive folder?

**Comment by acgaron** [comment]
sure! give me one second

On Tue, Apr 26, 2016 at 10:55 AM, Aaron Hill <notifications@github.com>
wrote:

> I'm not sure which iteration is the definitive version. Could you move old
> versions to an archive folder?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/acgaron/ML_2016/issues/1>
>



-- 
Andrew Garon
Statistician at Measure of America
Candidate, M.S. of Urban Policy Analysis and Management
Milano School of Public Engagement at the New School
(415) 299 2825

**Comment by aaronxhill** [comment]
i updated the dashboard assuming iteration 9 is the final version; let me know if it's a different version

**Comment by acgaron** [comment]
I will refer to both as we discuss the classification assignment; iteration 8 is the 82% TP rate, but at the cost of a 60ish% TN rate. So I modified to create iteration 9, which has a 66% TP / 80% TN. So 9 in the dashboard is fine, and if someone beats my TP rate I'll switch to 8.
